version: '3.7'

services:
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.4.0
    container_name: elasticsearch 
    environment:
      - http.host=0.0.0.0
      - transport.host=127.0.0.1
      - node.name=es01
      - cluster.name=esddp
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    restart: always 
    volumes:
      - esdata01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - es01
volumes:
    esdata01:
      driver: local
networks:
    es01:
      driver: bridge
