version: '3.7'

services:
  es01:
    image: elasticsearch:${ELASTIC_VERSION}
    container_name: elasticsearch 
    environment:
      - cluster.name=esddp
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    restart: on-failure
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - data-portal_default
volumes:
  esdata1:
    driver: local

networks:
  data-portal_default:
         external: true

